version: "3"

services:
  redis:
    hostname: redis
    container_name: redis
    image: "redis"
    restart: always

  bot:
    container_name: zeronebot
    build: .
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - ./config/.env
    depends_on:
      - redis