server:
  port: 8082

bot:
  name: ZeroneSocialBot
  key: 6669420600:AAExPavK52XlqdwCShUbSM8KRZZC5TL0rCY

zerone:
  page_size: 5
  photo: https://socialnet-bucket.s3.eu-north-1.amazonaws.com/zerone.png
  welcome: Привет! Мы создали это место, чтобы вы смогли развиваться, чувствовать себя максимально комфортно в кругу приятных людей. Это сообщество профессионалов, объединённых одной идеей — с помощью кода, магия станет реальностью!

http:
  url: http://${BACKEND_HOST}:${BACKEND_PORT}/api/v1
  agent: Mozilla/5.0

websocket:
  url: ws://${BACKEND_HOST}:${BACKEND_PORT}/api/v1/ws